# Generated via: macrotype macrotype/types macrotype/modules/emit.py
# Do not edit by hand
from macrotype.types.ir import Ty

def from_type(obj: object) -> Ty: ...
def normalize_annotation(obj: object) -> object: ...
