# Generated via: macrotype macrotype/types macrotype/modules/emit.py
# Do not edit by hand
from typing import Any

from macrotype.types.ir import Ty, TyRoot

EllipsisType = ellipsis

def unparse(t: Ty) -> Any: ...
def unparse_top(t: TyRoot) -> Any: ...
def _apply_annos(inner: Any, tree) -> Any: ...
def _unparse(n: Ty) -> Any: ...
def _unparse_no_annos(n: Ty) -> Any: ...
