# Generated via: macrotype macrotype/types macrotype/modules/emit.py
# Do not edit by hand
from typing import Any

from macrotype.modules.scanner import ModuleInfo
from macrotype.modules.symbols import Symbol

INDENT: str

def emit_module(mi: ModuleInfo) -> list[str]: ...
def collect_all_annotations(mi: ModuleInfo) -> list[Any]: ...
def flatten_annotation_atoms(ann: Any) -> set[Any]: ...
def build_name_map(atoms: set[Any], context: dict[str, Any]) -> dict[Any, str]: ...
def stringify_annotation(ann: Any, name_map: dict[Any, str]) -> str: ...
def _emit_symbol(sym: Symbol, name_map: dict[Any, str], *, indent: int) -> list[str]: ...
