from typing import Any, Callable

from macrotype.modules.ir import ClassDecl, FuncDecl, ModuleDecl

ModuleType = module

def _is_dunder(name: str) -> bool: ...
def scan_module(mod: module) -> ModuleDecl: ...
def _scan_function(fn: Callable[..., Any]) -> FuncDecl: ...
def _scan_class(cls: type) -> ClassDecl: ...
