# Generated via: macrotype macrotype/modules/validate.py -o __macrotype__/macrotype/modules/validate.pyi
# Do not edit by hand
from macrotype.modules.scanner import ModuleInfo
from macrotype.modules.symbols import Site, Symbol

class ModuleValidationError(TypeError): ...

def validate(mi: ModuleInfo) -> ModuleInfo: ...
def _validate_symbol(sym: Symbol, *, in_class: bool, in_td: bool) -> Symbol: ...
def _validate_site(site: Site, *, in_class: bool, in_td: bool) -> Site: ...
