# Generated via: macrotype macrotype -o __macrotype__/macrotype
# Do not edit by hand
from pathlib import Path

def _default_output_path(path: Path, cwd: Path, *, is_file: bool) -> Path: ...

def _stdout_write(lines: list[str], command: str | None) -> None: ...

def main(argv: list[str] | None) -> int: ...
