# Generated via: macrotype macrotype
# Do not edit by hand
from pathlib import Path

def _default_output_path(path: Path, cwd: Path, *, is_file: bool) -> Path: ...

def _stdout_write(lines: list[str], command: None | str) -> None: ...

def main(argv: None | list[str]) -> int: ...
