# Generated via: macrotype macrotype/validate.py -o __macrotype__/macrotype/validate.pyi
# Do not edit by hand
from macrotype.types_ir import Ty, TyApp
from typing import Literal, Literal

class TypeValidationError(TypeError): ...

Context = Literal

def validate(t: NormalizedTy) -> ValidatedTy: ...

def _v(node: Ty, *, ctx: Literal['top', 'tuple_items', 'call_params', 'concat_args', 'other']) -> None: ...

def _validate_literal_value(v: object) -> None: ...

def _validate_concatenate(node: TyApp) -> None: ...
