# Generated via: macrotype macrotype/modules/transformers/add_comment.py -o __macrotype__/macrotype/modules/transformers/add_comment.pyi
# Do not edit by hand
from macrotype.modules.ir import Decl, ModuleDecl

ModuleType = module

def _line_comment(line: str) -> None | str: ...

def _extract_name(line: str) -> None | str: ...

def _build_comment_map_from_lines(lines: list[str]) -> dict[str, str]: ...

def _build_comment_map(obj: module | type) -> dict[str, str]: ...

def _attach(sym: Decl, obj: None | object, cmap: dict[str, str]) -> None: ...

def add_comments(mi: ModuleDecl) -> None: ...
