# Generated via: macrotype macrotype/modules/transformers/enum.py -o __macrotype__/macrotype/modules/transformers/enum.pyi
# Do not edit by hand
from enum import EnumType

from macrotype.modules.symbols import AliasSymbol, ClassSymbol, ModuleInfo

def _enum_members(klass: EnumType) -> list[AliasSymbol]: ...
def _auto_enum_methods(klass: type) -> set[str]: ...
def _transform_class(sym: ClassSymbol, cls: type) -> None: ...
def transform_enums(mi: ModuleInfo) -> None: ...
