from enum import EnumType

from macrotype.modules.ir import AliasDecl, ClassDecl, ModuleDecl

def _enum_members(klass: EnumType) -> list[AliasDecl]: ...
def _auto_enum_methods(klass: type) -> set[str]: ...
def _transform_class(sym: ClassDecl, cls: type) -> None: ...
def transform_enums(mi: ModuleDecl) -> None: ...
