# Generated via: macrotype macrotype/modules/transformers/enum.py -o __macrotype__/macrotype/modules/transformers/enum.pyi
# Do not edit by hand
from enum import EnumType

from macrotype.modules.ir import ClassDecl, ModuleDecl, TypeDefDecl

def _enum_members(klass: EnumType) -> list[TypeDefDecl]: ...
def _auto_enum_methods(klass: type) -> set[str]: ...
def _transform_class(sym: ClassDecl, cls: type) -> None: ...
def transform_enums(mi: ModuleDecl) -> None: ...
