from typing import Any

from macrotype.modules.ir import ClassDecl, FuncDecl, ModuleDecl

def _normalize_function(sym: FuncDecl, fn: Any, *, is_method: bool) -> None: ...
def _normalize_class(sym: ClassDecl, cls: type) -> None: ...
def normalize_flags(mi: ModuleDecl) -> None: ...
