from macrotype.modules.symbols import ClassSymbol, FuncSymbol, ModuleInfo
from typing import Any

def _normalize_function(sym: FuncSymbol, fn: Any, *, is_method: bool) -> None: ...
def _normalize_class(sym: ClassSymbol, cls: type) -> None: ...
def normalize_flags(mi: ModuleInfo) -> None: ...
