from macrotype.meta_types import get_overloads
from macrotype.modules.symbols import ClassSymbol, FuncSymbol, ModuleInfo
from typing import Any, Callable

_get_overloads = get_overloads

def _annotation_for_value(value: Any) -> Any: ...
def _make_literal_overload(
    fn: Callable[..., Any], args: tuple, kwargs: dict, result: Any
) -> Callable[..., Any]: ...
def _expand_function(fn: Callable[..., Any], sym: FuncSymbol) -> list[FuncSymbol]: ...
def _get_function(cls: None | type, sym: FuncSymbol) -> Callable[..., Any] | None: ...
def _transform_class(sym: ClassSymbol, cls: type) -> None: ...
def expand_overloads(mi: ModuleInfo) -> None: ...
