# Generated via: macrotype macrotype/modules/transformers/param_default.py -o __macrotype__/macrotype/modules/transformers/param_default.pyi
# Do not edit by hand
from typing import Any, Callable

from macrotype.modules.ir import ClassDecl, FuncDecl, ModuleDecl

def _infer_function(sym: FuncDecl, fn: Callable[..., Any]) -> None: ...
def _transform_class(sym: ClassDecl, cls: type) -> None: ...
def infer_param_defaults(mi: ModuleDecl) -> None: ...
