from typing import Any

from macrotype.modules.ir import ClassDecl, ModuleDecl

def _transform_class(sym: ClassDecl, cls: type[Any]) -> None: ...
def prune_protocol_methods(mi: ModuleDecl) -> None: ...
