from macrotype.modules.symbols import ClassSymbol, ModuleInfo

def _transform_class(sym: ClassSymbol, cls: type, td_meta: type) -> None: ...
def prune_inherited_typeddict_fields(mi: ModuleInfo) -> None: ...
